# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RZllMg0V2GFMtDB0tobzzOAU15V7QXJabsq26lv/bpXqhjtBtHUVoh3Sb2OcFocWPaUiQOfXe8fgWtB9a00IwHyIYfixRfH8B4naxCmIuxeSns/sm3Xc06m3kqApQNoOOmhF8tO+e0Xq8VokG4d4CaF06dmDhm0fVR/lVRNXcos2TmglB9oo7htrFlicqtJqNBLz/5KTgmV7QdzriyG6Zhb5UnTSsh+aFgVvdSZM9OnvZZxf0Myv0TVTn5/gi5EzmQjpBsw9Fn/VlAg7/6uxLHf/GB86V5r6j3s+A+mccIXz+rDrDkVHqxgY2+wP0Bn7Q0n3Yp8piBKBEJZMrEOja7OEUYgMlqOAmJLWd8I3IpM/0Gcoc8j9prsLzlN2v2FbX8YHO6ntUdONJ9jDpLCZv9j2tR04nebn+l6Hz4iJmJMz08cY9o6JwrfvLUgGRHm/NXuf1i5IyISsDcOgTjYFw4cJ1lmjyIcQB1hXtchJiPjmXWGiKdxc3yMlHRdheA1MwOcb+PJAHeZproOQ6Z4R/1THHt3v7YAUkqA5jyH1Ne0k+fxdworV428u3icpwi9K4rv0N7bFxbcDC+URvQi9p0TqYSqCADh6QmxQsKjXVfmetMTo+Mvwkz0RXASjfSePppI0bHYalJCT5nfOPPOj5CbdX63yvqwYn5ViHKEWwTk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
