appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: RZllMg0V2GFMtDB0tobzzOAU15V7QXJabsq26lv/bpXqhjtBtHUVoh3Sb2OcFocWPaUiQOfXe8fgWtB9a00IwHyIYfixRfH8B4naxCmIuxeSns/sm3Xc06m3kqApQNoOOmhF8tO+e0Xq8VokG4d4CaF06dmDhm0fVR/lVRNXcos2TmglB9oo7htrFlicqtJqNBLz/5KTgmV7QdzriyG6Zhb5UnTSsh+aFgVvdSZM9OnvZZxf0Myv0TVTn5/gi5EzmQjpBsw9Fn/VlAg7/6uxLHf/GB86V5r6j3s+A+mccIXz+rDrDkVHqxgY2+wP0Bn7Q0n3Yp8piBKBEJZMrEOja7OEUYgMlqOAmJLWd8I3IpM/0Gcoc8j9prsLzlN2v2FbX8YHO6ntUdONJ9jDpLCZv9j2tR04nebn+l6Hz4iJmJMz08cY9o6JwrfvLUgGRHm/NXuf1i5IyISsDcOgTjYFw4cJ1lmjyIcQB1hXtchJiPjmXWGiKdxc3yMlHRdheA1MwOcb+PJAHeZproOQ6Z4R/1THHt3v7YAUkqA5jyH1Ne0k+fxdworV428u3icpwi9K4rv0N7bFxbcDC+URvQi9p0TqYSqCADh6QmxQsKjXVfmetMTo+Mvwkz0RXASjfSePppI0bHYalJCT5nfOPPOj5CbdX63yvqwYn5ViHKEWwTk=}
